### ISSUE TITLE
Security/Blackholed every time on POST

### ISSUE THREAD

**Issue by mrthan** [CakeDC/Config#10]
I've just updated to the latest commits (and moved the default view into my main app to override as instructed).

When I submit the config form it's being Blackholed everytime. If I remove the line

``` php
public $components = array('Security');
```

from _ConfigAppController.php_ then it POSTs and updates the config data correctly. I believe I've had to do the same in the past.

Is this an issue related to the plugin or something I'm doing - I can't tell. Is there something that'll clearly tell me what's triggering the blackhole?

I can guess it's related to the fact that all the fields are user generate perhaps: http://book.cakephp.org/2.0/en/core-libraries/components/security-component.html

**Comment by mrthan** [comment]
OK, I'm getting the "auth" blackhole error "‘auth’ Indicates a form validation error, or a controller/action mismatch error."

Is there something about the suggest form submit URL that it's not liking perhaps?

**Comment by burzum** [comment]
I've just tried to reproduce this without success. This must be an issue specific to whatever you do. What CakePHP version? Please try master branch of CakePHP that's what I've tried.

Are you using an AJAX call? Then you'll have to white-list the fields.
